# Azure Database for MySQL
spring:
    datasource:
        url: jdbc:mysql://${MYSQL_HOST}.mysql.database.azure.com:3306/${MYSQL_DATABASE_NAME}?useSSL=true&requireSSL=FALSE
        username: ${MYSQL_USER}@${MYSQL_HOST}
        password: ${MYSQL_PASSWORD}
    jpa:
        open-in-view: false