# Postgres driver connection
# Azure Database for PostgreSQL
spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}.postgres.database.azure.com:5432/${POSTGRES_DATABASE_NAME}?user=${POSTGRES_USER}@${POSTGRES_HOST}&password=${POSTGRES_PASSWORD}&sslmode=require
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
